reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit)

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  
disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace # tab-specific rule below
  - function_parameter_count
  - valid_docs
  - todo
  - line_length
  - trailing_comma
  - notification_center_detachment
  - fallthrough
